df <- read.csv("C:\\Users\\GOPI CHAND\\Downloads\\DATA SETS\\customer_chrun.csv")
print(df)
dim(df)
head(df)
tail(df)
library(dplyr)
summary(df)
View(df)
colnames(df)
names(df)
str(df)
is.null(df)
is.array(df)
is.atomic(df)
is.data.frame(df)
is.complex(df)
is.double(df)
is.environment(df)

summary(df)
duplicated_rows<-duplicated(df)
names(df)[names(df)=="gender"]<-"Gender"
names(df)[names(df)=="Gender"]<-"gender"
write_csv(df,"C:\\Users\\GOPI CHAND\\Downloads\\DATA SETS\\customer_chrun.csv")
head(sort(df$TotalCharges))
tail(sort(df$TotalCharges))
head(sort(df$tenure),bins=13)
tail(sort(df$tenure),n=13)
dim(df %>% filter(df$Churn=='yes',df$Contract=='month-to-month'))
dim(df %>% filter(df$Contract=='month-to-month'))
par(mfrow=c(2,2))
plot(df$tenure~df$MonthlyCharges,main='tenure vs.monthly charges', xlab ='charges',ylab ='tenure',col=3)
plot(df$tenure~df$TotalCharges,main='totalcharges vs.tenure',xlab='charges',ylab = 'tenure', col=4)
plot(df$MonthlyCharges~df$TotalCharges,main='total vs.monthly',xlab='total',ylab = 'monthly',col=6)
par(mfrow=c(1,1))
a<-hist(df$tenure,xlim = c(0,80),breaks = 20,main = 'tenure freq histo',xlab = 'tenure',ylab = 'freq',col = 3)
text(a$mids,a$counts,labels = a$counts, adj = c(0.5,1))
b<-hist(df$TotalCharges,xlim = c(0,100), breaks = 30,main = 'totalcharges freq histo',xlab = 'total',ylab ='freq ',col = 6)
text(b$mids, b$counts,labels = b$counts, adj = c(0.5,1))
c<-hist(df$MonthlyCharges, xlim=c(0,110), breaks = 10, main = 'monthlycharges freq histo', xlab = 'monthly', ylab = 'freq', col = 4)
text(c$mids,c$counts,labels=c$counts,adj=c(0.5,1))
library(ggplot2)
df %>% ggplot(aes(x=TotalCharges,fill=Churn))+geom_density(alpha=0.8)+scale_fill_manual(values = c('red','green'))+labs(tittle='total charges density split chrun vs non churn')
df %>% ggplot(aes(x=MonthlyCharges,fill=Churn))+geom_density(alpha=0.8)+scale_fill_manual(values = c('yellow','red'))+labs(tittle='monthly charges density split chrun vs non churn')
df %>% ggplot(aes(x=tenure, fill=Churn))+geom_density(alpha = 0.8)+scale_fill_manual(values = c('pink','purple'))+labs(tittle='tenure density split chrun and splite chrun')
